### ISSUE TITLE
Allow sensors for close position and config item for assumed state

### ISSUE THREAD

**Issue by Alfiegerner** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#10]
Hi,

Thanks for this - I'd made the tweaks to call my custom scripts and not send stop commands and then found your code, D'oh!

I was wondering if you'd consider introducing the other tweaks I'd made (happy to make a pull request):

An optional configuration for a sensor that indicates if cover is closed.  

```
  @property
    def is_closed(self):
        """Return if the cover is closed."""
        door_sensor = self.hass.states.get(self._closed_sensor)
        return door_sensor is None or door_sensor.state == self._closed_sensor_state
```

I'm using this with a garage door where people will be opening / closing outside of HA controls this would help stop getting cover out of sync.

My other current tweak is to set assumed_state to False - leaving it as True means both Up and Down arrows are available e.g.  when closed, which screws up underlying  actions required to operate door.

Having that as an optional item defaulting to True would help - out of interest are you seeing any UI oddness like arrows being available when they shouldn't be with that set to True?

Thanks!

**Comment by Alfiegerner** [comment]
Just a thought on the assumed_state, having it return false if fully open or close would fix the issue where arrows appear functional when they shouldn't be - would that work for other users?

**Comment by nagyrobi** [comment]
That's on purpose like this on this component. As [I've tried to describe in the readme](https://github.com/nagyrobi/home-assistant-custom-components-cover-rf-time-based#some-tips-when-using-this-component-with-tasmota-rf-bridge-in-automations), since there's no feedback from the cover about its current state, state is assumed based on the last command sent. And since it may happen that real state and HA state are out of sync, the quickest and easiest way to fix it is to be able to just change the state manually in HA. That of course triggers a command to be sent but it's normal.

As for setting the cover's state in HA based on external sensors - this is a good idea. I already thought of implementing a more universal method by having a dedicated service call type for setting such states (not only closed, but also open or even middle positions, based on where one can physically place a sensor).

**Comment by Alfiegerner** [comment]
Ok thanks I think I understand the assumed state logic now and why that makes all the buttons available, will keep my tweaks local.

Calls to set state and position from external trigger are a great idea, let me know if you want a tester.
