### ISSUE TITLE
feature request - delay start/stop (compute the percentages separately for 3 zones)

### ISSUE THREAD

**Issue by Flopescu** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#16]
Hi, 

Thank you for your work! Much appreciated.

I've set up my rollers and they're working great, thanks.
But I would like to have a small enhancement - to have the rollers show the open percentage synced with the percentage of the height of the window (ie if they show 75% they should be about 75% of the window height).

My rollers are spending quite a lot of time (about 5-6 seconds) to unroll and start lifting up, while getting to fully open takes about 24 seconds. This is translating to show 60% open when they are only 30-35% compared with the window height.

Maybe we can split the time traveling up/down into 3 parts and calculate the percentages for each of them, something like:

0  ---  3 ----------------- 97---100
| ----- | ------------------ | ----- |
   t1                    t2                    t3

That would make the percentages more accurate, and we can allow for different timings on each different motor. 

Do you think this can be easily achieved?
Thank you very much!
Florin

**Comment by nagyrobi** [comment]
Fully agree with you. 

Unfortunately it's not me who wrote the timing part of the component, and as far as I understand, it's relying on other (knx) components built-in Home Assistant.

Maybe somebody can take the time to rewrite that part.

**Comment by JeroLajHub** [comment]
Firstly thanks for the superb custom component.

I was about to pull a similar request so I support this one above.

To be sure it is the same, let me explain my purpose : 
- I have roller shutters.
- When the bottom slat of it just reaches the bottom of the windows while closing, there is still gaps between the slats letting enter the light through the shutter ; the moto continues to roll down 2 sec more so that all gaps are closes dans slats at their lower.
- Reversely, when opening is asked from the totally closed shutter, 2 sec are needed to opening the gaps between slats and only after the shutter (the buttom-slat) begins to move up.
- Taking account such a non-linear move would be a very refined improvement of the custom component !

I guess I can do it without asking you anything.
- I should be able to make it outside of the component with an automation to monitor the move when reaching the below, with your "set_known_position" option for adjustment, but it would be heavy and inelegant, wouldn' it.
- May be I could do it at the scrypt.yaml level but I have no guess how to do it right now.

But that would me so much more elegant and beneficial to everybody if done inside your custom component.

As I may not be aware of the constraint to code such a great custom-component, I think of many different ways to implement it, should one skirt such constraints : 
- as a first option,  I thought of a non-linear implementation as @Flopescu has suggested... but your reply tells us it is outside your reach (xknx) - I stilll wonder if a intermediate linear function would do the trick (between position shown to end-user and position for xknx move)
- As a second option, I wonder if you would be able to implement a negative position in your CC but only show from 0 to 100 positions : with adding a parameter such as "no_move_delay" of eg. 3 sec while "traveling_time_up" of eg. 30 sec, positions would go from -10 to 100 in 33 sec but you would enter xknx only after 3s and with 0 position.
- As a third option, I noticed that may be 0 and 100 position were special because asking to go respectively down and up with no stop command at an assumed time needed for reaching the position (the shutter stops itself at the end) ; may be you can implement that openingduring the first 3 sec "set_know_position" to 1.

OK I am trying to help but I am only at the conceptual level. I will be pleased to helpd anyhow but I have never coded. One time or another I should have a look at your code files.

**Comment by nagyrobi** [comment]
Nice concepts.

**Comment by JeroLajHub** [comment]
> Nice concepts.

Thanks, I would be happy to  let you find a way 😃

**Comment by nagyrobi** [comment]
Me too, be my guest. ;)

**Comment by JeroLajHub** [comment]
> Me too, be my guest. ;)

I may try looking at your code the next week-end. It would be a first for me !
