### ISSUE TITLE
Interrupt previous send command (script) with new one.

### ISSUE THREAD

**Issue by gid204** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#41]
Hi,

I'm not sure if this is possible at all or if it is a limitation of my RF device (Broadlink RM PRO+) but I'm wondering if there could be an option to interrupt the previous script call to start the next one.

Reason/Use case: 
If my blinds are closed and I want to open then very slightly, around 1%-3% for example. I notice that my broadlink will send the open command and only once that is done (once broadlink LED goes off), will it send the stop command. The issue is the stop command should have been set earlier, given the time it takes for my blinds to open completely.

Cheers!

**Comment by peterhoe** [comment]
I use the following for this similar use case scenario

Then I can set cover % regardless of whether it's open closed or partial. Takes a bit of tweaking on the open close timing side, but good enough for what I'm after

I also use broadlink rm pro for my  blinds

https://github.com/nagyrobi/home-assistant-custom-components-cover-rf-time-based<https://github.com/nagyrobi/home-assistant-custom-components-cover-rf-time-based#:~:text=Star%2042-,Time%2Dbased%20cover%20with%20customizable%20scripts%20or%20entity%20to%20trigger,information%20based%20on%20external%20sensors.>

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: gid204 ***@***.***>
Sent: Monday, May 30, 2022 10:45:55 AM
To: nagyrobi/home-assistant-custom-components-cover-rf-time-based ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nagyrobi/home-assistant-custom-components-cover-rf-time-based] Interrupt previous send command (script) with new one. (Issue #41)


Hi,

I'm not sure if this is possible or if it is a limitation of my RF device (Broadlink RM PRO+) at all but I'm wondering if there could be an option to interrupt the previous script call to start the next one.

Reason/Use case:
If my blinds are closed and I want to open then very slightly, around 1%-3% for example. I notice that my broadlink will send the open command and only once that is done (once broadlink LED goes off), will it send the stop command. The issue is the stop command should have been set earlier, given the time it takes for my blinds to open completely.

Cheers!

**Comment by gid204** [comment]
Hey @peterhoe the link provided seems to be broken…

**Comment by peterhoe** [comment]
How about this?

https://github.com/barmazu/home-assistant-custom-components-cover-rf-time-based

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by peterhoe** [comment]
I may also be misunderstanding your request given I'm reading on my tiny phone screen

**Comment by gid204** [comment]
Ye that link works.
How does that custom component differ from the one this issue has been opened in?

**Comment by peterhoe** [comment]
Damn using my phone to read, and not using my glasses

 

My bad

**Comment by nagyrobi** [comment]
> I'm not sure if this is possible at all or if it is a limitation of my RF device (Broadlink RM PRO+) but I'm wondering if there could be an option to interrupt the previous script call to start the next one.

Unfortunately it's not possible because the scripts employed by this component are all _one shot_ meaning that they only run to trigger the command specific to your RF device. The fact that your `broadlink will send the open command and only once that is done (once broadlink LED goes off), will it send the stop command` is uncontrollable from this component. That is Broadlink-specific. Try searching for Broadlink support for disabling this feature.

**Comment by gid204** [comment]
> >
> is uncontrollable from this component. That is Broadlink-specific. Try searching for Broadlink support for disabling this feature.
>>
No problem I thought this might be the case.

> How does the Broadlink know how much time has to wait?

What do you mean by this?

**Comment by gid204** [comment]
> > once broadlink LED goes off
> 
> How much time until broadlink LED goes off?

The LED stays on for about 2 seconds from when the signal is sent. 
My interpretation of this is it takes about 2 seconds to send the command. Even though the device (my blinds) respond pretty much instantly.

**Comment by nagyrobi** [comment]
Ok that Broadlink is shitty. You should search for a way to disable that.
Open solutions like Sonoff RF Bridge running ESPHome or Tasmota don't produce this kind of behavior.
