### ISSUE TITLE
FR Allow templates for travelling_time_up/down

### ISSUE THREAD

**Issue by VDRainer** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#6]
The last one today. :smile: 

Hope it's ok to request features in the issue tracker.

It would be nice to configure the travelling settings with an input_number or other templates.
For example:
```
travelling_time_up: "{{ states('input_number.cover_up') }}"
```
- This would make adjusting the times easier without HA restart.
- Some of my older covers need one or two seconds more if it's realy cold outside.

**Comment by nagyrobi** [comment]
I tried to change it to accept templates, but it seems that it breaks HA's `core.restore_state` functionality, which is in charge of keeping the states of the entities during restarts.

I wouldn't touch that part because this is an important feature, previous timed cover components didn't support that, this is finally working well like this.

I suggest to use some lubricant to maintain the cover motors. I also have about a dozen which need to be unmounted completely because they also need a capacitor replacement inside the tube, as after 10 years they started to behave strange in in cold weather.
